[project]
name = "investlogflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.5",
    "django-environ>=0.13.0",
    "django-tailwind>=4.4.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "django-stubs>=6.0.4",
    "django-tailwind[cookiecutter,honcho,reload]>=4.4.2",
    "django-watchfiles>=1.4.0",
]
