# Generated by Django 6.0.5 on 2026-05-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('cik', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('primary_exchange', models.CharField(max_length=255)),
                ('composite_figi', models.CharField(max_length=12)),
                ('share_class_figi', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('financialproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.financialproduct')),
                ('issuer', models.CharField(max_length=255)),
                ('maturity_date', models.DateField()),
            ],
            bases=('tracker.financialproduct',),
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('financialproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.financialproduct')),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
            bases=('tracker.financialproduct',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('financialproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.financialproduct')),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
            bases=('tracker.financialproduct',),
        ),
        migrations.CreateModel(
            name='ActualPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=24)),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('investments', models.ManyToManyField(related_name='portfolios', to='tracker.investment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='users.organization')),
            ],
        ),
    ]
