# Generated by Django 6.0.5 on 2026-05-26 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date_invested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
