# Generated by Django 6.0.5 on 2026-05-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_investment_date_invested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='investments',
        ),
        migrations.AddField(
            model_name='investment',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='tracker.portfolio'),
            preserve_default=False,
        ),
    ]
