# Generated by Django 6.0.5 on 2026-05-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_portfolio_investments_investment_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActualPrice',
            new_name='PriceRecord',
        ),
    ]
