# Generated by Django 6.0.5 on 2026-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_actualprice_pricerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerecord',
            old_name='price',
            new_name='close_price',
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='open_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='volume',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
