# Generated by Django 6.0.5 on 2026-05-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_price_pricerecord_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='date_recorded',
            field=models.DateTimeField(),
        ),
    ]
