# Generated by Django 6.0.5 on 2026-05-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_pricerecord_date_recorded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerecord',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.AlterUniqueTogether(
            name='pricerecord',
            unique_together={('product', 'date_recorded')},
        ),
    ]
