# Generated by Django 6.0.5 on 2026-05-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_pricerecord_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='amount_invested',
            new_name='amount_invested_per_share',
        ),
    ]
